name: Fetch GW2 Stats

on:
  schedule:
    - cron: '7 11,17,23 * * *'
  workflow_dispatch:       # Allows manual triggers

jobs:
  fetch-gw2-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Fetch account data
      - name: Fetch Account Data
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GW2_API_TOKEN }}" \
            "https://api.guildwars2.com/v2/account?&v=2025-01-01T01:00:00.000Z" \
            -o account.json

      # Fetch achievements data
      - name: Fetch Achievements Data
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GW2_API_TOKEN }}" \
            "https://api.guildwars2.com/v2/account/achievements" \
            -o achievements.json

      # Fetch wallet data
      - name: Fetch Wallet Data
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GW2_API_TOKEN }}" \
            "https://api.guildwars2.com/v2/account/wallet" \
            -o wallet.json

      # Fetch materials data
      - name: Fetch Materials Data
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GW2_API_TOKEN }}" \
            "https://api.guildwars2.com/v2/account/materials" \
            -o materials.json
          
      # Process and combine the data
      - name: Process JSON Data
        run: |
          timestamp=$(date +"%Y-%m-%dT%H:%M:%S%z")
          jq -n \
            --arg timestamp "$timestamp" \
            --slurpfile account account.json \
            --slurpfile achievements achievements.json \
            --slurpfile wallet wallet.json \
            --slurpfile materials materials.json \
            '{
              "timestamp": $timestamp,
              "id": $account[0].id,
              "wvw_rank": $account[0].wvw.rank,
              "wvw_kills": ($achievements[0][] | select(.id == 283).current),
              "coin": ($wallet[0][] | select(.id == 1).value),
              "mystic_clovers": ($materials[0][] | select(.id == 19675).count),
              "mystic_coins": ($materials[0][] | select(.id == 19976).count),
              "ancient_bone": ($materials[0][] | select(.id == 24358).count),
              "armored_scale": ($materials[0][] | select(.id == 24289).count),
              "elaborate_totem": ($materials[0][] | select(.id == 24300).count),
              "pile_of_crystalline_dust": ($materials[0][] | select(.id == 24277).count),
              "powerful_venom_sac": ($materials[0][] | select(.id == 24283).count),
              "vial_of_powerful_blood": ($materials[0][] | select(.id == 24295).count),
              "vicious_claw": ($materials[0][] | select(.id == 24351).count),
              "vicious_fang": ($materials[0][] | select(.id == 24357).count)
            }' > gw2.json
        
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add gw2.json
          git commit -m "Update GW2 stats" || exit 0
          git push
